kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: airgapped-docs
  namespace: fleet-default
spec:
  repo: https://github.com/bgulla/fleet-demos.git
  branch: main
  targets:
  - name: carbide
    clusterSelector:
      matchLabels:
        carbide: enabled
  paths:
  - "./carbide/airgapped-docs/helm"
