# installCRDs: "true"
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ngrok-operator
  namespace: kube-system
spec:
  repo: https://zufardhiyaulhaq.com/ngrok-operator/charts/releases/
  chart: ngrok-operator
  targetNamespace: ngrok-operator
  version: v1.3.0
    
